# Generated by Django 6.0 on 2025-12-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripshit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="url",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="personage",
            name="url",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="starship",
            name="url",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
