# Generated by Django 6.0 on 2025-12-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripshit", "0002_movie_url_personage_url_starship_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="starship",
            name="films",
        ),
        migrations.AddField(
            model_name="starship",
            name="films",
            field=models.ManyToManyField(
                blank=True, related_name="starships", to="tripshit.movie"
            ),
        ),
    ]
