# Generated by Django 6.0 on 2025-12-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripshit", "0003_remove_starship_films_starship_films"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personage",
            name="starship",
        ),
        migrations.AddField(
            model_name="personage",
            name="starships",
            field=models.ManyToManyField(
                blank=True, related_name="pilots", to="tripshit.starship"
            ),
        ),
        migrations.RemoveField(
            model_name="personage",
            name="films",
        ),
        migrations.AddField(
            model_name="personage",
            name="films",
            field=models.ManyToManyField(
                blank=True, related_name="characters", to="tripshit.movie"
            ),
        ),
    ]
