# Generated by Django 6.0 on 2025-12-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripshit", "0004_remove_personage_starship_personage_starships_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personage",
            name="birth_year",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="personage",
            name="height",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="personage",
            name="mass",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="starship",
            name="max_atmosphering_speed",
            field=models.CharField(max_length=20),
        ),
    ]
