# Generated by Django 6.0 on 2025-12-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripshit", "0005_alter_personage_birth_year_alter_personage_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="starship",
            name="pilots",
            field=models.ManyToManyField(
                blank=True, related_name="piloted_starships", to="tripshit.personage"
            ),
        ),
        migrations.AlterField(
            model_name="personage",
            name="starships",
            field=models.ManyToManyField(
                blank=True, related_name="members", to="tripshit.starship"
            ),
        ),
    ]
